name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy repository to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ vars.SERVER_PORT }}
          source: "."
          target: "/home/sergey/tgcard"

      - name: Deploy using Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ vars.SERVER_PORT }}
          script: |
            cd /home/sergey/tgcard
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
            echo "WEB_URL=${{ secrets.WEB_URL }}" >> .env
            docker compose down
            docker compose up --build -d
